import '../core/models/widget_node.dart';
import '../core/models/screen_model.dart';

// Advanced Dart code generator — WidgetNode tree → clean Flutter code
class DartCodeGen {

  // Full project: main.dart with all screens
  static String generateProject(List<ForgeScreen> screens) {
    final buf = StringBuffer();
    buf.writeln("import 'package:flutter/material.dart';");
    buf.writeln();
    buf.writeln('// 🔥 Generated by GAX Forge');
    buf.writeln('// Edit freely — this is production-ready Flutter code');
    buf.writeln();
    buf.writeln('void main() => runApp(const MyApp());');
    buf.writeln();
    buf.writeln('class MyApp extends StatelessWidget {');
    buf.writeln('  const MyApp({super.key});');
    buf.writeln();
    buf.writeln('  @override');
    buf.writeln('  Widget build(BuildContext context) {');
    buf.writeln('    return MaterialApp(');
    buf.writeln("      title: 'GAX App',");
    buf.writeln('      debugShowCheckedModeBanner: false,');
    buf.writeln('      theme: ThemeData(');
    buf.writeln('        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),');
    buf.writeln('        useMaterial3: true,');
    buf.writeln('      ),');
    buf.writeln('      home: const ${_className(screens.first.name)}(),');
    buf.writeln('    );');
    buf.writeln('  }');
    buf.writeln('}');
    buf.writeln();

    for (final screen in screens) {
      buf.write(_generateScreenClass(screen));
      buf.writeln();
    }

    return buf.toString();
  }

  // Single screen class
  static String generateScreen(ForgeScreen screen) {
    final buf = StringBuffer();
    buf.writeln("import 'package:flutter/material.dart';");
    buf.writeln();
    buf.writeln('// 🔥 Generated by GAX Forge — ${screen.name}');
    buf.writeln();
    buf.write(_generateScreenClass(screen));
    return buf.toString();
  }

  static String _generateScreenClass(ForgeScreen screen) {
    final buf = StringBuffer();
    final className = _className(screen.name);
    final nodes = screen.sortedNodes;

    buf.writeln('class $className extends StatelessWidget {');
    buf.writeln('  const $className({super.key});');
    buf.writeln();
    buf.writeln('  @override');
    buf.writeln('  Widget build(BuildContext context) {');
    buf.writeln('    return Scaffold(');
    buf.writeln('      backgroundColor: ${_colorExpr(screen.backgroundColor)},');
    buf.writeln('      body: Stack(');
    buf.writeln('        children: [');

    for (final node in nodes) {
      if (!node.visible) continue;
      buf.writeln('          Positioned(');
      buf.writeln('            left: ${node.x.round()}.0,');
      buf.writeln('            top: ${node.y.round()}.0,');
      buf.writeln('            width: ${node.width.round()}.0,');
      buf.writeln('            height: ${node.height.round()}.0,');
      buf.writeln('            child: ${_generateWidget(node, 12)},');
      buf.writeln('          ),');
    }

    buf.writeln('        ],');
    buf.writeln('      ),');
    buf.writeln('    );');
    buf.writeln('  }');
    buf.writeln('}');
    return buf.toString();
  }

  static String _generateWidget(WidgetNode node, int indent) {
    final p = node.props;
    final pad = ' ' * indent;

    switch (node.type) {
      case WType.container: return _container(node, p, pad, indent);
      case WType.text: return _text(node, p, pad);
      case WType.image: return _image(node, p, pad);
      case WType.button: return _button(node, p, pad);
      case WType.iconButton: return _iconButton(node, p, pad);
      case WType.textField: return _textField(node, p, pad);
      case WType.card: return _card(node, p, pad, indent);
      case WType.icon: return _icon(node, p, pad);
      case WType.switchW: return _switchW(node, p, pad);
      case WType.slider: return _slider(node, p, pad);
      case WType.checkbox: return _checkbox(node, p, pad);
      case WType.divider: return _divider(node, p, pad);
      case WType.listTile: return _listTile(node, p, pad);
      case WType.circleAvatar: return _circleAvatar(node, p, pad);
      case WType.row: return _flex(node, p, pad, indent, isRow: true);
      case WType.column: return _flex(node, p, pad, indent, isRow: false);
      case WType.stack: return _stack(node, p, pad, indent);
      case WType.listView: return _listView(node, p, pad);
      case WType.gridView: return _gridView(node, p, pad);
      case WType.appBar: return _appBar(node, p, pad);
    }
  }

  // ── Widget code generators ────────────────────────────────

  static String _container(WidgetNode n, Map p, String pad, int indent) {
    final radius = (p['borderRadius'] as num?)?.toDouble() ?? 0;
    final padding = (p['padding'] as num?)?.toDouble() ?? 0;
    final grad = p['gradientEnabled'] == true;
    final shadow = p['shadowEnabled'] == true;

    final deco = StringBuffer('BoxDecoration(');
    if (grad) {
      deco.write('\n$pad    gradient: LinearGradient('
          'colors: [${_colorExpr(p['gradientStart'])}, ${_colorExpr(p['gradientEnd'])}]),');
    } else {
      deco.write('\n$pad    color: ${_colorExpr(p['color'])},');
    }
    if (radius > 0) {
      deco.write('\n$pad    borderRadius: BorderRadius.circular($radius),');
    }
    final bw = (p['borderWidth'] as num?)?.toDouble() ?? 0;
    if (bw > 0) {
      deco.write('\n$pad    border: Border.all(color: ${_colorExpr(p['borderColor'])}, width: $bw),');
    }
    if (shadow) {
      deco.write('\n$pad    boxShadow: [BoxShadow('
          'color: ${_colorExpr(p['shadowColor'])}.withOpacity(0.3), '
          'blurRadius: ${p['shadowBlur']}, '
          'offset: Offset(${p['shadowX']}, ${p['shadowY']}))],');
    }
    deco.write('\n$pad  )');

    final childCode = n.children.isEmpty
        ? ''
        : '\n$pad  child: ${_generateWidget(n.children.first, indent + 4)},';

    return '''Container(
$pad  width: ${n.width.round()}.0,
$pad  height: ${n.height.round()}.0,
$pad  padding: const EdgeInsets.all($padding),
$pad  decoration: $deco,$childCode
$pad)''';
  }

  static String _text(WidgetNode n, Map p, String pad) {
    final decoration = p['decoration'] == 'underline'
        ? 'TextDecoration.underline'
        : p['decoration'] == 'lineThrough'
            ? 'TextDecoration.lineThrough' : 'TextDecoration.none';
    return '''Text(
$pad  '${(p['text'] ?? 'Text').toString().replaceAll("'", "\\'")}',
$pad  textAlign: ${_textAlign(p['textAlign'])},
$pad  style: const TextStyle(
$pad    fontSize: ${(p['fontSize'] as num?)?.toDouble() ?? 16},
$pad    color: ${_colorExpr(p['color'])},
$pad    fontWeight: ${_fontWeight(p['fontWeight'])},
$pad    letterSpacing: ${(p['letterSpacing'] as num?)?.toDouble() ?? 0},
$pad    height: ${(p['lineHeight'] as num?)?.toDouble() ?? 1.4},
$pad    decoration: $decoration,
$pad  ),
$pad)''';
  }

  static String _image(WidgetNode n, Map p, String pad) {
    final radius = (p['borderRadius'] as num?)?.toDouble() ?? 0;
    final fit = _boxFit(p['fit']);
    if (radius > 0) {
      return '''ClipRRect(
$pad  borderRadius: BorderRadius.circular($radius),
$pad  child: Image.network(
$pad    '${p['imageUrl'] ?? ''}',
$pad    width: ${n.width.round()}.0,
$pad    height: ${n.height.round()}.0,
$pad    fit: $fit,
$pad    errorBuilder: (_, __, ___) => const Icon(Icons.broken_image),
$pad  ),
$pad)''';
    }
    return '''Image.network(
$pad  '${p['imageUrl'] ?? ''}',
$pad  width: ${n.width.round()}.0,
$pad  height: ${n.height.round()}.0,
$pad  fit: $fit,
$pad  errorBuilder: (_, __, ___) => const Icon(Icons.broken_image),
$pad)''';
  }

  static String _button(WidgetNode n, Map p, String pad) {
    final style = p['style'] ?? 'elevated';
    final radius = (p['borderRadius'] as num?)?.toDouble() ?? 8;
    final label = (p['label'] ?? 'Button').toString().replaceAll("'", "\\'");

    final shapeStr = radius > 0
        ? 'shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular($radius)),'
        : '';

    switch (style) {
      case 'outlined':
        return '''SizedBox(
$pad  width: ${n.width.round()}.0, height: ${n.height.round()}.0,
$pad  child: OutlinedButton(
$pad    onPressed: () {},
$pad    style: OutlinedButton.styleFrom(foregroundColor: ${_colorExpr(p['backgroundColor'])}, $shapeStr),
$pad    child: const Text('$label'),
$pad  ),
$pad)''';
      case 'text':
        return '''TextButton(
$pad  onPressed: () {},
$pad  child: const Text('$label', style: TextStyle(color: ${_colorExpr(p['backgroundColor'])})),
$pad)''';
      default:
        return '''SizedBox(
$pad  width: ${n.width.round()}.0, height: ${n.height.round()}.0,
$pad  child: ElevatedButton(
$pad    onPressed: () {},
$pad    style: ElevatedButton.styleFrom(
$pad      backgroundColor: ${_colorExpr(p['backgroundColor'])},
$pad      foregroundColor: ${_colorExpr(p['foregroundColor'])},
$pad      $shapeStr
$pad    ),
$pad    child: const Text('$label'),
$pad  ),
$pad)''';
    }
  }

  static String _iconButton(WidgetNode n, Map p, String pad) {
    return '''IconButton(
$pad  onPressed: () {},
$pad  icon: const Icon(Icons.${p['icon'] ?? 'star'}, size: ${p['size'] ?? 24}),
$pad  color: ${_colorExpr(p['color'])},
$pad  tooltip: '${p['tooltip'] ?? ''}',
$pad)''';
  }

  static String _textField(WidgetNode n, Map p, String pad) {
    final border = p['borderType'] == 'underline'
        ? 'UnderlineInputBorder()'
        : p['borderType'] == 'none'
            ? 'InputBorder.none'
            : 'OutlineInputBorder(borderRadius: BorderRadius.circular(${(p['borderRadius'] as num?)?.toDouble() ?? 8}))';

    return '''SizedBox(
$pad  width: ${n.width.round()}.0,
$pad  child: TextField(
$pad    obscureText: ${p['obscureText'] == true},
$pad    decoration: const InputDecoration(
$pad      hintText: '${p['hintText'] ?? ''}',
$pad      labelText: '${p['labelText'] ?? ''}',
$pad      border: $border,
$pad      filled: true,
$pad    ),
$pad  ),
$pad)''';
  }

  static String _card(WidgetNode n, Map p, String pad, int indent) {
    final childCode = n.children.isEmpty
        ? 'const SizedBox.shrink()'
        : _generateWidget(n.children.first, indent + 4);
    return '''Card(
$pad  elevation: ${(p['elevation'] as num?)?.toDouble() ?? 4},
$pad  color: ${_colorExpr(p['color'])},
$pad  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(${(p['borderRadius'] as num?)?.toDouble() ?? 12})),
$pad  clipBehavior: Clip.antiAlias,
$pad  child: SizedBox(width: ${n.width.round()}.0, height: ${n.height.round()}.0,
$pad    child: $childCode),
$pad)''';
  }

  static String _icon(WidgetNode n, Map p, String pad) {
    return '''Icon(
$pad  Icons.${p['icon'] ?? 'star'},
$pad  color: ${_colorExpr(p['color'])},
$pad  size: ${(p['size'] as num?)?.toDouble() ?? 32},
$pad)''';
  }

  static String _switchW(WidgetNode n, Map p, String pad) {
    return '''Switch(
$pad  value: ${p['value'] == true},
$pad  activeColor: ${_colorExpr(p['activeColor'])},
$pad  onChanged: (val) { /* TODO */ },
$pad)''';
  }

  static String _slider(WidgetNode n, Map p, String pad) {
    return '''Slider(
$pad  value: ${(p['value'] as num?)?.toDouble() ?? 0.5},
$pad  min: ${(p['min'] as num?)?.toDouble() ?? 0.0},
$pad  max: ${(p['max'] as num?)?.toDouble() ?? 1.0},
$pad  activeColor: ${_colorExpr(p['activeColor'])},
$pad  onChanged: (val) { /* TODO */ },
$pad)''';
  }

  static String _checkbox(WidgetNode n, Map p, String pad) {
    return '''Checkbox(
$pad  value: ${p['value'] == true},
$pad  activeColor: ${_colorExpr(p['activeColor'])},
$pad  onChanged: (val) { /* TODO */ },
$pad)''';
  }

  static String _divider(WidgetNode n, Map p, String pad) {
    if (p['vertical'] == true) {
      return 'const VerticalDivider(color: ${_colorExpr(p['color'])}, thickness: ${(p['thickness'] as num?)?.toDouble() ?? 1})';
    }
    return '''Divider(
$pad  color: ${_colorExpr(p['color'])},
$pad  thickness: ${(p['thickness'] as num?)?.toDouble() ?? 1},
$pad  indent: ${(p['indent'] as num?)?.toDouble() ?? 0},
$pad  endIndent: ${(p['endIndent'] as num?)?.toDouble() ?? 0},
$pad)''';
  }

  static String _listTile(WidgetNode n, Map p, String pad) {
    return '''ListTile(
$pad  leading: const Icon(Icons.${p['leadingIcon'] ?? 'circle'}),
$pad  title: const Text('${(p['title'] ?? 'Title').toString().replaceAll("'", "\\'")}'),
$pad  subtitle: const Text('${(p['subtitle'] ?? '').toString().replaceAll("'", "\\'")}'),
$pad  trailing: const Icon(Icons.${p['trailingIcon'] ?? 'chevron_right'}),
$pad  onTap: () {},
$pad)''';
  }

  static String _circleAvatar(WidgetNode n, Map p, String pad) {
    final url = p['imageUrl']?.toString() ?? '';
    if (url.isNotEmpty) {
      return '''CircleAvatar(
$pad  radius: ${(p['radius'] as num?)?.toDouble() ?? 28},
$pad  backgroundImage: NetworkImage('$url'),
$pad)''';
    }
    return '''CircleAvatar(
$pad  radius: ${(p['radius'] as num?)?.toDouble() ?? 28},
$pad  backgroundColor: ${_colorExpr(p['backgroundColor'])},
$pad  child: Text('${p['initials'] ?? 'GX'}',
$pad    style: const TextStyle(color: ${_colorExpr(p['foregroundColor'])},
$pad      fontWeight: FontWeight.bold)),
$pad)''';
  }

  static String _flex(WidgetNode n, Map p, String pad, int indent, {required bool isRow}) {
    final type = isRow ? 'Row' : 'Column';
    final main = _mainAxisAlignment(p['mainAxisAlignment']);
    final cross = _crossAxisAlignment(p['crossAxisAlignment']);
    final children = n.children.isEmpty
        ? '${' ' * (indent + 4)}const SizedBox.shrink(),'
        : n.children.map((c) => '${' ' * (indent + 4)}${_generateWidget(c, indent + 4)},').join('\n');
    return '''$type(
$pad  mainAxisAlignment: $main,
$pad  crossAxisAlignment: $cross,
$pad  children: [
$children
$pad  ],
$pad)''';
  }

  static String _stack(WidgetNode n, Map p, String pad, int indent) {
    final children = n.children.isEmpty
        ? '${' ' * (indent + 4)}const Placeholder(),'
        : n.children.map((c) => '${' ' * (indent + 4)}${_generateWidget(c, indent + 4)},').join('\n');
    return '''Stack(
$pad  children: [
$children
$pad  ],
$pad)''';
  }

  static String _listView(WidgetNode n, Map p, String pad) {
    final count = (p['itemCount'] as num?)?.toInt() ?? 5;
    return '''ListView.builder(
$pad  itemCount: $count,
$pad  itemBuilder: (context, index) => ListTile(
$pad    title: Text('Item \${index + 1}'),
$pad  ),
$pad)''';
  }

  static String _gridView(WidgetNode n, Map p, String pad) {
    final cols = (p['crossAxisCount'] as num?)?.toInt() ?? 2;
    return '''GridView.builder(
$pad  gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
$pad    crossAxisCount: $cols,
$pad    mainAxisSpacing: ${(p['mainAxisSpacing'] as num?)?.toDouble() ?? 8},
$pad    crossAxisSpacing: ${(p['crossAxisSpacing'] as num?)?.toDouble() ?? 8},
$pad  ),
$pad  itemCount: ${cols * 2},
$pad  itemBuilder: (context, index) => Container(
$pad    color: Colors.grey.shade200,
$pad    child: Center(child: Text('\${index + 1}')),
$pad  ),
$pad)''';
  }

  static String _appBar(WidgetNode n, Map p, String pad) {
    return '''AppBar(
$pad  title: const Text('${(p['title'] ?? 'Title').toString().replaceAll("'", "\\'")}'),
$pad  backgroundColor: ${_colorExpr(p['backgroundColor'])},
$pad  foregroundColor: ${_colorExpr(p['foregroundColor'])},
$pad  centerTitle: ${p['centerTitle'] == true},
$pad  elevation: ${(p['elevation'] as num?)?.toDouble() ?? 0},
$pad)''';
  }

  // ── Expression helpers ────────────────────────────────────

  static String _colorExpr(dynamic hex) {
    if (hex == null || hex.toString().isEmpty) return 'Colors.transparent';
    final s = hex.toString().replaceAll('#', '').trim();
    if (s.length == 6) return 'const Color(0xFF${s.toUpperCase()})';
    if (s.length == 8) return 'const Color(0x${s.toUpperCase()})';
    return 'Colors.grey';
  }

  static String _textAlign(dynamic v) {
    switch (v) {
      case 'center': return 'TextAlign.center';
      case 'right': return 'TextAlign.right';
      case 'justify': return 'TextAlign.justify';
      default: return 'TextAlign.left';
    }
  }

  static String _fontWeight(dynamic v) {
    switch (v) {
      case 'bold': return 'FontWeight.bold';
      case 'w300': return 'FontWeight.w300';
      case 'w500': return 'FontWeight.w500';
      case 'w600': return 'FontWeight.w600';
      case 'w700': return 'FontWeight.w700';
      case 'w900': return 'FontWeight.w900';
      default: return 'FontWeight.normal';
    }
  }

  static String _boxFit(dynamic v) {
    switch (v) {
      case 'contain': return 'BoxFit.contain';
      case 'fill': return 'BoxFit.fill';
      case 'fitWidth': return 'BoxFit.fitWidth';
      case 'fitHeight': return 'BoxFit.fitHeight';
      case 'none': return 'BoxFit.none';
      default: return 'BoxFit.cover';
    }
  }

  static String _mainAxisAlignment(dynamic v) {
    switch (v) {
      case 'center': return 'MainAxisAlignment.center';
      case 'end': return 'MainAxisAlignment.end';
      case 'spaceBetween': return 'MainAxisAlignment.spaceBetween';
      case 'spaceAround': return 'MainAxisAlignment.spaceAround';
      case 'spaceEvenly': return 'MainAxisAlignment.spaceEvenly';
      default: return 'MainAxisAlignment.start';
    }
  }

  static String _crossAxisAlignment(dynamic v) {
    switch (v) {
      case 'start': return 'CrossAxisAlignment.start';
      case 'end': return 'CrossAxisAlignment.end';
      case 'stretch': return 'CrossAxisAlignment.stretch';
      default: return 'CrossAxisAlignment.center';
    }
  }

  static String _className(String name) {
    if (name.isEmpty) return 'MyScreen';
    return name[0].toUpperCase() +
        name.substring(1).replaceAll(' ', '').replaceAll('-', '');
  }
}
