import '../core/models/widget_node.dart';
import '../core/models/screen_model.dart';

// StatefulWidget code generator — Switch + Slider ka interactive code
class StatefulCodeGen {
  /// Generates a StatefulWidget for screens that have interactive widgets
  static String generateStatefulScreen(ForgeScreen screen) {
    final hasInteractive = _hasInteractive(screen.nodes);
    final className = _className(screen.name);

    final buf = StringBuffer();
    buf.writeln("import 'package:flutter/material.dart';");
    buf.writeln();
    buf.writeln('// 🔥 Generated by GAX Forge — ${screen.name}');
    buf.writeln('// StatefulWidget — interactive widgets included');
    buf.writeln();

    if (hasInteractive) {
      buf.writeln('class $className extends StatefulWidget {');
      buf.writeln('  const $className({super.key});');
      buf.writeln('  @override');
      buf.writeln('  State<$className> createState() => _${className}State();');
      buf.writeln('}');
      buf.writeln();
      buf.writeln('class _${className}State extends State<$className> {');
      _writeStateVars(buf, screen.nodes, '  ');
      buf.writeln();
      buf.writeln('  @override');
      buf.writeln('  Widget build(BuildContext context) {');
      buf.writeln('    return Scaffold(');
      buf.writeln(
          '      backgroundColor: ${_colorExpr(screen.backgroundColor)},');
      _writeBody(buf, screen, '      ');
      buf.writeln('    );');
      buf.writeln('  }');
      buf.writeln('}');
    } else {
      buf.writeln('class $className extends StatelessWidget {');
      buf.writeln('  const $className({super.key});');
      buf.writeln('  @override');
      buf.writeln('  Widget build(BuildContext context) {');
      buf.writeln('    return Scaffold(');
      buf.writeln(
          '      backgroundColor: ${_colorExpr(screen.backgroundColor)},');
      _writeBody(buf, screen, '      ');
      buf.writeln('    );');
      buf.writeln('  }');
      buf.writeln('}');
    }

    return buf.toString();
  }

  static bool _hasInteractive(List<WidgetNode> nodes) {
    for (final n in nodes) {
      if (n.type == WType.switchW ||
          n.type == WType.slider ||
          n.type == WType.checkbox) return true;
      if (_hasInteractive(n.children)) return true;
    }
    return false;
  }

  static void _writeStateVars(
      StringBuffer buf, List<WidgetNode> nodes, String pad) {
    for (final n in nodes) {
      final varName = _varName(n.id);
      switch (n.type) {
        case WType.switchW:
          buf.writeln(
              '$pad bool $varName = ${n.props['value'] == true};  // ${n.displayName}');
          break;
        case WType.slider:
          buf.writeln(
              '$pad double ${varName}Val = ${(n.props['value'] as num?)?.toDouble() ?? 0.5};  // ${n.displayName}');
          break;
        case WType.checkbox:
          buf.writeln(
              '$pad bool $varName = ${n.props['value'] == true};  // ${n.displayName}');
          break;
        default:
          break;
      }
      if (n.children.isNotEmpty) _writeStateVars(buf, n.children, pad);
    }
  }

  static void _writeBody(
      StringBuffer buf, ForgeScreen screen, String pad) {
    buf.writeln('${pad}body: Stack(');
    buf.writeln('$pad  children: [');
    for (final n in screen.sortedNodes) {
      if (!n.visible) continue;
      buf.writeln('$pad    Positioned(');
      buf.writeln('$pad      left: ${n.x.round()}.0,');
      buf.writeln('$pad      top: ${n.y.round()}.0,');
      buf.writeln('$pad      width: ${n.width.round()}.0,');
      buf.writeln('$pad      height: ${n.height.round()}.0,');
      buf.writeln('$pad      child: ${_genWidget(n, 8)},');
      buf.writeln('$pad    ),');
    }
    buf.writeln('$pad  ],');
    buf.writeln('$pad),');
  }

  static String _genWidget(WidgetNode n, int indent) {
    final pad = ' ' * indent;
    final varName = _varName(n.id);

    switch (n.type) {
      case WType.switchW:
        return '''Switch(
$pad  value: $varName,
$pad  activeColor: ${_colorExpr(n.props['activeColor'])},
$pad  onChanged: (val) => setState(() => $varName = val),
$pad)''';

      case WType.slider:
        return '''Slider(
$pad  value: ${varName}Val,
$pad  min: ${(n.props['min'] as num?)?.toDouble() ?? 0.0},
$pad  max: ${(n.props['max'] as num?)?.toDouble() ?? 1.0},
$pad  activeColor: ${_colorExpr(n.props['activeColor'])},
$pad  onChanged: (val) => setState(() => ${varName}Val = val),
$pad)''';

      case WType.checkbox:
        return '''Checkbox(
$pad  value: $varName,
$pad  activeColor: ${_colorExpr(n.props['activeColor'])},
$pad  onChanged: (val) => setState(() => $varName = val ?? false),
$pad)''';

      case WType.button:
        return '''ElevatedButton(
$pad  onPressed: () { /* TODO: add action */ },
$pad  style: ElevatedButton.styleFrom(
$pad    backgroundColor: ${_colorExpr(n.props['backgroundColor'])},
$pad    foregroundColor: ${_colorExpr(n.props['foregroundColor'])},
$pad  ),
$pad  child: const Text('${n.props['label'] ?? 'Button'}'),
$pad)''';

      default:
        // Fall back to basic codegen
        return 'const SizedBox(width: ${n.width.round()}, height: ${n.height.round()})';
    }
  }

  static String _colorExpr(dynamic hex) {
    if (hex == null || hex.toString().isEmpty) return 'Colors.transparent';
    final s = hex.toString().replaceAll('#', '').trim();
    if (s.length == 6) return 'const Color(0xFF${s.toUpperCase()})';
    return 'Colors.grey';
  }

  static String _className(String name) {
    if (name.isEmpty) return 'MyScreen';
    return name[0].toUpperCase() +
        name.substring(1).replaceAll(' ', '').replaceAll('-', '');
  }

  // Shorten UUID to a valid Dart variable name
  static String _varName(String id) {
    final short = id.replaceAll('-', '').substring(0, 8);
    return '_var$short';
  }
}
