import 'package:dart_style/dart_style.dart';
import '../models/models.dart';
import 'constants.dart';

/// Dart code generator - Canvas widgets ko Flutter code mein convert karta hai
/// Isse user ko clean, formatted Dart code milti hai jo directly use kar sakte hain

class CodeGenerator {
  static final DartFormatter _formatter = DartFormatter();

  /// Generate complete Flutter code from project
  static String generateCode(ProjectModel project) {
    final buffer = StringBuffer();

    // Add imports
    buffer.writeln("import 'package:flutter/material.dart';");
    buffer.writeln();

    // Generate widget class
    buffer.writeln('/// Generated by Gax Forge');
    buffer.writeln('/// Project: ${project.name}');
    buffer.writeln('/// Generated at: ${DateTime.now().toIso8601String()}');
    buffer.writeln();
    buffer.writeln('class GeneratedScreen extends StatelessWidget {');
    buffer.writeln('  const GeneratedScreen({super.key});');
    buffer.writeln();
    buffer.writeln('  @override');
    buffer.writeln('  Widget build(BuildContext context) {');
    buffer.writeln('    return Scaffold(');

    // Generate body
    if (project.widgets.isEmpty) {
      buffer.writeln('      body: const Center(');
      buffer.writeln('        child: Text(\'No widgets added yet\'),');
      buffer.writeln('      ),');
    } else {
      // Sort by z-index (order in list)
      final sortedWidgets = List<CanvasWidgetModel>.from(project.widgets);

      // Find root widgets (no parent)
      final rootWidgets = sortedWidgets.where((w) => w.parentId == null).toList();

      for (var widget in rootWidgets) {
        final code = _generateWidgetCode(widget, sortedWidgets, 3);
        buffer.write(code);
      }
    }

    buffer.writeln('    );');
    buffer.writeln('  }');
    buffer.writeln('}');

    // Format code
    try {
      return _formatter.format(buffer.toString());
    } catch (e) {
      // If formatting fails, return unformatted code
      return buffer.toString();
    }
  }

  /// Generate code for a single widget
  static String _generateWidgetCode(
    CanvasWidgetModel widget,
    List<CanvasWidgetModel> allWidgets,
    int indent,
  ) {
    final indentStr = '  ' * indent;
    final childIndent = '  ' * (indent + 1);

    switch (widget.type) {
      case WidgetType.container:
        return _generateContainerCode(widget, indent);
      case WidgetType.containerDecorated:
        return _generateDecoratedContainerCode(widget, indent);
      case WidgetType.text:
        return _generateTextCode(widget, indent);
      case WidgetType.icon:
        return _generateIconCode(widget, indent);
      case WidgetType.image:
        return _generateImageCode(widget, indent);
      case WidgetType.elevatedButton:
        return _generateElevatedButtonCode(widget, indent);
      case WidgetType.textButton:
        return _generateTextButtonCode(widget, indent);
      case WidgetType.outlinedButton:
        return _generateOutlinedButtonCode(widget, indent);
      case WidgetType.iconButton:
        return _generateIconButtonCode(widget, indent);
      case WidgetType.card:
        return _generateCardCode(widget, allWidgets, indent);
      case WidgetType.appBar:
        return _generateAppBarCode(widget, indent);
      case WidgetType.scaffold:
        return _generateScaffoldCode(widget, allWidgets, indent);
      case WidgetType.listTile:
        return _generateListTileCode(widget, indent);
      case WidgetType.circleAvatar:
        return _generateCircleAvatarCode(widget, indent);
      case WidgetType.divider:
        return _generateDividerCode(widget, indent);
      case WidgetType.chip:
        return _generateChipCode(widget, indent);
      case WidgetType.badge:
        return _generateBadgeCode(widget, indent);
      case WidgetType.linearProgressIndicator:
        return _generateLinearProgressCode(widget, indent);
      case WidgetType.circularProgressIndicator:
        return _generateCircularProgressCode(widget, indent);
      case WidgetType.switchWidget:
        return _generateSwitchCode(widget, indent);
      case WidgetType.checkbox:
        return _generateCheckboxCode(widget, indent);
      case WidgetType.radio:
        return _generateRadioCode(widget, indent);
      case WidgetType.row:
        return _generateRowCode(widget, allWidgets, indent);
      case WidgetType.column:
        return _generateColumnCode(widget, allWidgets, indent);
      case WidgetType.stack:
        return _generateStackCode(widget, allWidgets, indent);
      case WidgetType.wrap:
        return _generateWrapCode(widget, allWidgets, indent);
      case WidgetType.padding:
        return _generatePaddingCode(widget, allWidgets, indent);
      case WidgetType.center:
        return _generateCenterCode(widget, allWidgets, indent);
      case WidgetType.expanded:
        return _generateExpandedCode(widget, allWidgets, indent);
      case WidgetType.flexible:
        return _generateFlexibleCode(widget, allWidgets, indent);
    }
  }

  /// Generate Container code
  static String _generateContainerCode(CanvasWidgetModel widget, int indent) {
    final indentStr = '  ' * indent;
    final props = widget.properties;

    final color = _colorFromHex(props['color'] ?? '#E0E0E0');
    final width = props['width'] ?? widget.size.width;
    final height = props['height'] ?? widget.size.height;

    return '$indentStr Container(\n' +
        '$indentStr   width: $width,\n' +
        '$indentStr   height: $height,\n' +
        '$indentStr   color: $color,\n' +
        '$indentStr ),\n';
  }

  /// Generate Decorated Container code
  static String _generateDecoratedContainerCode(CanvasWidgetModel widget, int indent) {
    final indentStr = '  ' * indent;
    final childIndent = '  ' * (indent + 1);
    final props = widget.properties;

    final color = _colorFromHex(props['color'] ?? '#E0E0E0');
    final borderRadius = props['borderRadius'] ?? 0.0;
    final borderColor = _colorFromHex(props['borderColor'] ?? '#000000');
    final borderWidth = props['borderWidth'] ?? 0.0;

    return '$indentStr Container(\n' +
        '$indentStr   width: ${props['width'] ?? widget.size.width},\n' +
        '$indentStr   height: ${props['height'] ?? widget.size.height},\n' +
        '$indentStr   decoration: BoxDecoration(\n' +
        '$childIndent color: $color,\n' +
        '$childIndent borderRadius: BorderRadius.circular($borderRadius),\n' +
        '$childIndent border: Border.all(color: $borderColor, width: $borderWidth),\n' +
        '$indentStr   ),\n' +
        '$indentStr ),\n';
  }

  /// Generate Text code
  static String _generateTextCode(CanvasWidgetModel widget, int indent) {
    final indentStr = '  ' * indent;
    final props = widget.properties;

    final text = props['text'] ?? 'Text';
    final fontSize = props['fontSize'] ?? 16.0;
    final fontWeight = _fontWeightFromString(props['fontWeight'] ?? 'normal');
    final color = _colorFromHex(props['color'] ?? '#000000');
    final textAlign = _textAlignFromString(props['textAlign'] ?? 'left');

    return '$indentStr Text(\n' +
        "$indentStr   '$text',\n" +
        '$indentStr   style: TextStyle(\n' +
        '$indentStr     fontSize: $fontSize,\n' +
        '$indentStr     fontWeight: FontWeight.$fontWeight,\n' +
        '$indentStr     color: $color,\n' +
        '$indentStr   ),\n' +
        '$indentStr   textAlign: TextAlign.$textAlign,\n' +
        '$indentStr ),\n';
  }

  /// Generate Icon code
  static String _generateIconCode(CanvasWidgetModel widget, int indent) {
    final indentStr = '  ' * indent;
    final props = widget.properties;

    final iconName = props['iconName'] ?? 'Icons.star';
    final size = props['size'] ?? 24.0;
    final color = _colorFromHex(props['color'] ?? '#757575');

    return '$indentStr Icon(\n' +
        '$indentStr   $iconName,\n' +
        '$indentStr   size: $size,\n' +
        '$indentStr   color: $color,\n' +
        '$indentStr ),\n';
  }

  /// Generate Image code
  static String _generateImageCode(CanvasWidgetModel widget, int indent) {
    final indentStr = '  ' * indent;
    final props = widget.properties;

    final imageUrl = props['imageUrl'] ?? 'https://picsum.photos/200';
    final width = props['width'] ?? 100.0;
    final height = props['height'] ?? 100.0;
    final fit = props['fit'] ?? 'cover';

    return '$indentStr Image.network(\n' +
        "$indentStr   '$imageUrl',\n" +
        '$indentStr   width: $width,\n' +
        '$indentStr   height: $height,\n' +
        '$indentStr   fit: BoxFit.$fit,\n' +
        '$indentStr ),\n';
  }

  /// Generate ElevatedButton code
  static String _generateElevatedButtonCode(CanvasWidgetModel widget, int indent) {
    final indentStr = '  ' * indent;
    final props = widget.properties;

    final label = props['label'] ?? 'Button';
    final buttonColor = _colorFromHex(props['buttonColor'] ?? '#6750A4');
    final textColor = _colorFromHex(props['textColor'] ?? '#FFFFFF');

    return '$indentStr ElevatedButton(\n' +
        "$indentStr   onPressed: () {},\n" +
        '$indentStr   style: ElevatedButton.styleFrom(\n' +
        '$indentStr     backgroundColor: $buttonColor,\n' +
        '$indentStr     foregroundColor: $textColor,\n' +
        '$indentStr   ),\n' +
        "$indentStr   child: const Text('$label'),\n" +
        '$indentStr ),\n';
  }

  /// Generate TextButton code
  static String _generateTextButtonCode(CanvasWidgetModel widget, int indent) {
    final indentStr = '  ' * indent;
    final props = widget.properties;

    final label = props['label'] ?? 'Text Button';

    return '$indentStr TextButton(\n' +
        "$indentStr   onPressed: () {},\n" +
        "$indentStr   child: const Text('$label'),\n" +
        '$indentStr ),\n';
  }

  /// Generate OutlinedButton code
  static String _generateOutlinedButtonCode(CanvasWidgetModel widget, int indent) {
    final indentStr = '  ' * indent;
    final props = widget.properties;

    final label = props['label'] ?? 'Outlined';

    return '$indentStr OutlinedButton(\n' +
        "$indentStr   onPressed: () {},\n" +
        "$indentStr   child: const Text('$label'),\n" +
        '$indentStr ),\n';
  }

  /// Generate IconButton code
  static String _generateIconButtonCode(CanvasWidgetModel widget, int indent) {
    final indentStr = '  ' * indent;
    final props = widget.properties;

    final iconName = props['iconName'] ?? 'Icons.add';
    final iconSize = props['iconSize'] ?? 24.0;
    final color = _colorFromHex(props['color'] ?? '#757575');

    return '$indentStr IconButton(\n' +
        '$indentStr   icon: Icon($iconName, size: $iconSize, color: $color),\n' +
        '$indentStr   onPressed: () {},\n' +
        '$indentStr ),\n';
  }

  /// Generate Card code
  static String _generateCardCode(CanvasWidgetModel widget, List<CanvasWidgetModel> allWidgets, int indent) {
    final indentStr = '  ' * indent;
    final childIndent = '  ' * (indent + 2);
    final props = widget.properties;

    final elevation = props['elevation'] ?? 2.0;
    final color = _colorFromHex(props['color'] ?? '#FFFFFF');
    final borderRadius = props['borderRadius'] ?? 12.0;

    // Get children
    final children = allWidgets.where((w) => w.parentId == widget.id).toList();

    String childrenCode = '';
    if (children.isEmpty) {
      childrenCode = '$childIndent const Text(\'Card Content\'),\n';
    } else {
      for (var child in children) {
        childrenCode += _generateWidgetCode(child, allWidgets, indent + 2);
      }
    }

    return '$indentStr Card(\n' +
        '$indentStr   elevation: $elevation,\n' +
        '$indentStr   color: $color,\n' +
        '$indentStr   shape: RoundedRectangleBorder(\n' +
        '$indentStr     borderRadius: BorderRadius.circular($borderRadius),\n' +
        '$indentStr   ),\n' +
        '$indentStr   child: Padding(\n' +
        '$indentStr     padding: const EdgeInsets.all(16.0),\n' +
        childrenCode +
        '$indentStr   ),\n' +
        '$indentStr ),\n';
  }

  /// Generate AppBar code
  static String _generateAppBarCode(CanvasWidgetModel widget, int indent) {
    final indentStr = '  ' * indent;
    final props = widget.properties;

    final title = props['title'] ?? 'AppBar';
    final backgroundColor = _colorFromHex(props['backgroundColor'] ?? '#6750A4');
    final elevation = props['elevation'] ?? 0.0;
    final centerTitle = props['centerTitle'] ?? false;

    return '$indentStr AppBar(\n' +
        "$indentStr   title: const Text('$title'),\n" +
        '$indentStr   backgroundColor: $backgroundColor,\n' +
        '$indentStr   elevation: $elevation,\n' +
        '$indentStr   centerTitle: $centerTitle,\n' +
        '$indentStr   automaticallyImplyLeading: false,\n' +
        '$indentStr ),\n';
  }

  /// Generate Scaffold code
  static String _generateScaffoldCode(CanvasWidgetModel widget, List<CanvasWidgetModel> allWidgets, int indent) {
    final indentStr = '  ' * indent;
    final childIndent = '  ' * (indent + 2);
    final props = widget.properties;

    final backgroundColor = _colorFromHex(props['backgroundColor'] ?? '#FFFFFF');

    // Get children
    final children = allWidgets.where((w) => w.parentId == widget.id).toList();

    String bodyCode = '';
    if (children.isEmpty) {
      bodyCode = '$childIndent Container(color: $backgroundColor),\n';
    } else {
      for (var child in children) {
        bodyCode += _generateWidgetCode(child, allWidgets, indent + 2);
      }
    }

    return '$indentStr Container(\n' +
        '$indentStr   color: $backgroundColor,\n' +
        '$indentStr   child: $bodyCode' +
        '$indentStr ),\n';
  }

  /// Generate ListTile code
  static String _generateListTileCode(CanvasWidgetModel widget, int indent) {
    final indentStr = '  ' * indent;
    final props = widget.properties;

    final title = props['title'] ?? 'ListTile';
    final subtitle = props['subtitle'] ?? '';
    final leadingIcon = props['leadingIcon'] ?? 'Icons.list';
    final trailingIcon = props['trailingIcon'] ?? 'Icons.arrow_forward_ios';

    String result = '$indentStr ListTile(\n';
    result += "$indentStr   leading: Icon($leadingIcon),\n";
    result += "$indentStr   title: const Text('$title'),\n";
    if (subtitle.isNotEmpty) {
      result += "$indentStr   subtitle: const Text('$subtitle'),\n";
    }
    result += "$indentStr   trailing: Icon($trailingIcon),\n";
    result += '$indentStr ),\n';

    return result;
  }

  /// Generate CircleAvatar code
  static String _generateCircleAvatarCode(CanvasWidgetModel widget, int indent) {
    final indentStr = '  ' * indent;
    final props = widget.properties;

    final radius = props['radius'] ?? 20.0;
    final bgColor = _colorFromHex(props['backgroundColor'] ?? '#2196F3');
    final fgColor = _colorFromHex(props['foregroundColor'] ?? '#FFFFFF');
    final text = props['text'] ?? 'A';

    return '$indentStr CircleAvatar(\n' +
        "$indentStr   radius: $radius,\n" +
        "$indentStr   backgroundColor: $bgColor,\n" +
        "$indentStr   foregroundColor: $fgColor,\n" +
        "$indentStr   child: Text('$text'),\n" +
        '$indentStr ),\n';
  }

  /// Generate Divider code
  static String _generateDividerCode(CanvasWidgetModel widget, int indent) {
    final indentStr = '  ' * indent;
    final props = widget.properties;

    final thickness = props['thickness'] ?? 1.0;
    final color = _colorFromHex(props['color'] ?? '#E0E0E0');

    return '$indentStr Divider(\n' +
        '$indentStr   thickness: $thickness,\n' +
        '$indentStr   color: $color,\n' +
        '$indentStr ),\n';
  }

  /// Generate Chip code
  static String _generateChipCode(CanvasWidgetModel widget, int indent) {
    final indentStr = '  ' * indent;
    final props = widget.properties;

    final label = props['label'] ?? 'Chip';
    final bgColor = _colorFromHex(props['backgroundColor'] ?? '#E0E0E0');

    return '$indentStr Chip(\n' +
        "$indentStr   label: const Text('$label'),\n" +
        '$indentStr   backgroundColor: $bgColor,\n' +
        '$indentStr ),\n';
  }

  /// Generate Badge code
  static String _generateBadgeCode(CanvasWidgetModel widget, int indent) {
    final indentStr = '  ' * indent;
    final props = widget.properties;

    final label = props['label'] ?? '1';
    final bgColor = _colorFromHex(props['backgroundColor'] ?? '#F44336');

    return '$indentStr Badge(\n' +
        "$indentStr   label: Text('$label'),\n" +
        '$indentStr   backgroundColor: $bgColor,\n' +
        "$indentStr   child: const Icon(Icons.notifications),\n" +
        '$indentStr ),\n';
  }

  /// Generate LinearProgressIndicator code
  static String _generateLinearProgressCode(CanvasWidgetModel widget, int indent) {
    final indentStr = '  ' * indent;
    final props = widget.properties;

    final value = props['value'] ?? 0.5;
    final color = _colorFromHex(props['color'] ?? '#6750A4');
    final bgColor = _colorFromHex(props['backgroundColor'] ?? '#E0E0E0');

    return '$indentStr LinearProgressIndicator(\n' +
        '$indentStr   value: $value,\n' +
        '$indentStr   color: $color,\n' +
        '$indentStr   backgroundColor: $bgColor,\n' +
        '$indentStr ),\n';
  }

  /// Generate CircularProgressIndicator code
  static String _generateCircularProgressCode(CanvasWidgetModel widget, int indent) {
    final indentStr = '  ' * indent;
    final props = widget.properties;

    final size = props['size'] ?? 40.0;
    final color = _colorFromHex(props['color'] ?? '#6750A4');

    return '$indentStr SizedBox(\n' +
        '$indentStr   width: $size,\n' +
        '$indentStr   height: $size,\n' +
        '$indentStr   child: CircularProgressIndicator(\n' +
        '$indentStr     color: $color,\n' +
        '$indentStr   ),\n' +
        '$indentStr ),\n';
  }

  /// Generate Switch code
  static String _generateSwitchCode(CanvasWidgetModel widget, int indent) {
    final indentStr = '  ' * indent;
    final props = widget.properties;

    final value = props['value'] ?? false;
    final activeColor = _colorFromHex(props['activeColor'] ?? '#6750A4');

    return '$indentStr Switch(\n' +
        '$indentStr   value: $value,\n' +
        '$indentStr   activeColor: $activeColor,\n' +
        '$indentStr   onChanged: (value) {},\n' +
        '$indentStr ),\n';
  }

  /// Generate Checkbox code
  static String _generateCheckboxCode(CanvasWidgetModel widget, int indent) {
    final indentStr = '  ' * indent;
    final props = widget.properties;

    final value = props['value'] ?? false;
    final activeColor = _colorFromHex(props['activeColor'] ?? '#6750A4');

    return '$indentStr Checkbox(\n' +
        '$indentStr   value: $value,\n' +
        '$indentStr   activeColor: $activeColor,\n' +
        '$indentStr   onChanged: (value) {},\n' +
        '$indentStr ),\n';
  }

  /// Generate Radio code
  static String _generateRadioCode(CanvasWidgetModel widget, int indent) {
    final indentStr = '  ' * indent;
    final props = widget.properties;

    final value = props['value'] ?? 'a';
    final activeColor = _colorFromHex(props['activeColor'] ?? '#6750A4');

    return '$indentStr Radio<\n' +
        "$indentStr   String>(\n" +
        '$indentStr   value: \'$value\',\n' +
        '$indentStr   groupValue: null,\n' +
        '$indentStr   activeColor: $activeColor,\n' +
        '$indentStr   onChanged: (value) {},\n' +
        '$indentStr ),\n';
  }

  /// Generate Row code
  static String _generateRowCode(CanvasWidgetModel widget, List<CanvasWidgetModel> allWidgets, int indent) {
    final indentStr = '  ' * indent;
    final childIndent = '  ' * (indent + 1);
    final props = widget.properties;

    final mainAxisAlign = _mainAxisAlignFromString(props['mainAxisAlignment'] ?? 'start');
    final crossAxisAlign = _crossAxisAlignFromString(props['crossAxisAlignment'] ?? 'start');

    // Get children
    final children = allWidgets.where((w) => w.parentId == widget.id).toList();

    if (children.isEmpty) {
      return '$indentStr Row(\n' +
          '$indentStr   mainAxisAlignment: MainAxisAlignment.$mainAxisAlign,\n' +
          '$indentStr   crossAxisAlignment: CrossAxisAlignment.$crossAxisAlign,\n' +
          '$indentStr   children: const [],\n' +
          '$indentStr ),\n';
    }

    String childrenCode = '';
    for (var child in children) {
      childrenCode += _generateWidgetCode(child, allWidgets, indent + 1);
    }

    return '$indentStr Row(\n' +
        '$indentStr   mainAxisAlignment: MainAxisAlignment.$mainAxisAlign,\n' +
        '$indentStr   crossAxisAlignment: CrossAxisAlignment.$crossAxisAlign,\n' +
        '$indentStr   children: [\n' +
        childrenCode +
        '$indentStr   ],\n' +
        '$indentStr ),\n';
  }

  /// Generate Column code
  static String _generateColumnCode(CanvasWidgetModel widget, List<CanvasWidgetModel> allWidgets, int indent) {
    final indentStr = '  ' * indent;
    final childIndent = '  ' * (indent + 1);
    final props = widget.properties;

    final mainAxisAlign = _mainAxisAlignFromString(props['mainAxisAlignment'] ?? 'start');
    final crossAxisAlign = _crossAxisAlignFromString(props['crossAxisAlignment'] ?? 'start');

    // Get children
    final children = allWidgets.where((w) => w.parentId == widget.id).toList();

    if (children.isEmpty) {
      return '$indentStr Column(\n' +
          '$indentStr   mainAxisAlignment: MainAxisAlignment.$mainAxisAlign,\n' +
          '$indentStr   crossAxisAlignment: CrossAxisAlignment.$crossAxisAlign,\n' +
          '$indentStr   children: const [],\n' +
          '$indentStr ),\n';
    }

    String childrenCode = '';
    for (var child in children) {
      childrenCode += _generateWidgetCode(child, allWidgets, indent + 1);
    }

    return '$indentStr Column(\n' +
        '$indentStr   mainAxisAlignment: MainAxisAlignment.$mainAxisAlign,\n' +
        '$indentStr   crossAxisAlignment: CrossAxisAlignment.$crossAxisAlign,\n' +
        '$indentStr   children: [\n' +
        childrenCode +
        '$indentStr   ],\n' +
        '$indentStr ),\n';
  }

  /// Generate Stack code
  static String _generateStackCode(CanvasWidgetModel widget, List<CanvasWidgetModel> allWidgets, int indent) {
    final indentStr = '  ' * indent;
    final childIndent = '  ' * (indent + 1);

    // Get children
    final children = allWidgets.where((w) => w.parentId == widget.id).toList();

    if (children.isEmpty) {
      return '$indentStr Stack(\n' +
          '$indentStr   children: const [],\n' +
          '$indentStr ),\n';
    }

    String childrenCode = '';
    for (var child in children) {
      childrenCode += _generateWidgetCode(child, allWidgets, indent + 1);
    }

    return '$indentStr Stack(\n' +
        '$indentStr   children: [\n' +
        childrenCode +
        '$indentStr   ],\n' +
        '$indentStr ),\n';
  }

  /// Generate Wrap code
  static String _generateWrapCode(CanvasWidgetModel widget, List<CanvasWidgetModel> allWidgets, int indent) {
    final indentStr = '  ' * indent;
    final childIndent = '  ' * (indent + 1);

    // Get children
    final children = allWidgets.where((w) => w.parentId == widget.id).toList();

    if (children.isEmpty) {
      return '$indentStr Wrap(\n' +
          '$indentStr   children: const [],\n' +
          '$indentStr ),\n';
    }

    String childrenCode = '';
    for (var child in children) {
      childrenCode += _generateWidgetCode(child, allWidgets, indent + 1);
    }

    return '$indentStr Wrap(\n' +
        '$indentStr   children: [\n' +
        childrenCode +
        '$indentStr   ],\n' +
        '$indentStr ),\n';
  }

  /// Generate Padding code
  static String _generatePaddingCode(CanvasWidgetModel widget, List<CanvasWidgetModel> allWidgets, int indent) {
    final indentStr = '  ' * indent;
    final childIndent = '  ' * (indent + 1);
    final props = widget.properties;

    final padding = props['padding'] ?? 16.0;

    // Get children
    final children = allWidgets.where((w) => w.parentId == widget.id).toList();

    if (children.isEmpty) {
      return '$indentStr Padding(\n' +
          '$indentStr   padding: EdgeInsets.all($padding),\n' +
          '$indentStr   child: Container(),\n' +
          '$indentStr ),\n';
    }

    String childrenCode = '';
    for (var child in children) {
      childrenCode += _generateWidgetCode(child, allWidgets, indent + 1);
    }

    return '$indentStr Padding(\n' +
        '$indentStr   padding: EdgeInsets.all($padding),\n' +
        '$indentStr   child: $childrenCode' +
        '$indentStr ),\n';
  }

  /// Generate Center code
  static String _generateCenterCode(CanvasWidgetModel widget, List<CanvasWidgetModel> allWidgets, int indent) {
    final indentStr = '  ' * indent;
    final childIndent = '  ' * (indent + 1);

    // Get children
    final children = allWidgets.where((w) => w.parentId == widget.id).toList();

    if (children.isEmpty) {
      return '$indentStr Center(\n' +
          '$indentStr   child: Container(),\n' +
          '$indentStr ),\n';
    }

    String childrenCode = '';
    for (var child in children) {
      childrenCode += _generateWidgetCode(child, allWidgets, indent + 1);
    }

    return '$indentStr Center(\n' +
        '$indentStr   child: $childrenCode' +
        '$indentStr ),\n';
  }

  /// Generate Expanded code
  static String _generateExpandedCode(CanvasWidgetModel widget, List<CanvasWidgetModel> allWidgets, int indent) {
    final indentStr = '  ' * indent;
    final childIndent = '  ' * (indent + 1);

    // Get children
    final children = allWidgets.where((w) => w.parentId == widget.id).toList();

    if (children.isEmpty) {
      return '$indentStr Expanded(\n' +
          '$indentStr   child: Container(),\n' +
          '$indentStr ),\n';
    }

    String childrenCode = '';
    for (var child in children) {
      childrenCode += _generateWidgetCode(child, allWidgets, indent + 1);
    }

    return '$indentStr Expanded(\n' +
        '$indentStr   child: $childrenCode' +
        '$indentStr ),\n';
  }

  /// Generate Flexible code
  static String _generateFlexibleCode(CanvasWidgetModel widget, List<CanvasWidgetModel> allWidgets, int indent) {
    final indentStr = '  ' * indent;
    final childIndent = '  ' * (indent + 1);

    // Get children
    final children = allWidgets.where((w) => w.parentId == widget.id).toList();

    if (children.isEmpty) {
      return '$indentStr Flexible(\n' +
          '$indentStr   child: Container(),\n' +
          '$indentStr ),\n';
    }

    String childrenCode = '';
    for (var child in children) {
      childrenCode += _generateWidgetCode(child, allWidgets, indent + 1);
    }

    return '$indentStr Flexible(\n' +
        '$indentStr   child: $childrenCode' +
        '$indentStr ),\n';
  }

  // Helper methods for converting values

  static String _colorFromHex(String hex) {
    final hexCode = hex.replaceAll('#', '');
    if (hexCode.length == 6) {
      final value = int.parse(hexCode, radix: 16);
      return 'Color(0xFF$hexCode)';
    } else if (hexCode.length == 8) {
      final value = int.parse(hexCode, radix: 16);
      return 'Color(0x$hexCode)';
    }
    return 'Colors.grey';
  }

  static String _fontWeightFromString(String weight) {
    switch (weight.toLowerCase()) {
      case 'bold':
        return 'bold';
      case 'w100':
        return 'w100';
      case 'w200':
        return 'w200';
      case 'w300':
        return 'w300';
      case 'w400':
        return 'w400';
      case 'w500':
        return 'w500';
      case 'w600':
        return 'w600';
      case 'w700':
        return 'w700';
      case 'w800':
        return 'w800';
      case 'w900':
        return 'w900';
      default:
        return 'w400';
    }
  }

  static String _textAlignFromString(String align) {
    switch (align.toLowerCase()) {
      case 'left':
        return 'left';
      case 'right':
        return 'right';
      case 'center':
        return 'center';
      case 'justify':
        return 'justify';
      default:
        return 'left';
    }
  }

  static String _mainAxisAlignFromString(String align) {
    switch (align.toLowerCase()) {
      case 'start':
        return 'start';
      case 'center':
        return 'center';
      case 'end':
        return 'end';
      case 'spaceBetween':
        return 'spaceBetween';
      case 'spaceAround':
        return 'spaceAround';
      case 'spaceEvenly':
        return 'spaceEvenly';
      default:
        return 'start';
    }
  }

  static String _crossAxisAlignFromString(String align) {
    switch (align.toLowerCase()) {
      case 'start':
        return 'start';
      case 'center':
        return 'center';
      case 'end':
        return 'end';
      case 'stretch':
        return 'stretch';
      case 'baseline':
        return 'baseline';
      default:
        return 'start';
    }
  }
}
