// lib/utils/export_utils.dart
// GAX Forge - Dart Code Generator & File Export

import 'dart:io';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../models/app_models.dart';

class ExportUtils {
  // ── Entry Point ─────────────────────────────
  static Future<void> exportProject(
      BuildContext context, GaxProject project) async {
    try {
      // Show loading
      showDialog(
        context: context,
        barrierDismissible: false,
        builder: (_) => const AlertDialog(
          content: Row(
            children: [
              CircularProgressIndicator(),
              SizedBox(width: 16),
              Text('Generating Dart code...'),
            ],
          ),
        ),
      );

      final files = <String, String>{};

      // Generate one dart file per screen
      for (int i = 0; i < project.screens.length; i++) {
        final screen = project.screens[i];
        final className = _toClassName(screen.name);
        final fileName = '${_toSnakeCase(screen.name)}_screen.dart';
        files[fileName] = _generateScreenFile(project, screen, className);
      }

      // Generate main.dart
      files['main.dart'] = _generateMainFile(project);

      // Generate pubspec.yaml hint
      files['pubspec_hint.yaml'] = _generatePubspecHint();

      // Save all files
      final dir = await getApplicationDocumentsDirectory();
      final exportDir =
          Directory('${dir.path}/gax_forge_export/${project.name}');
      await exportDir.create(recursive: true);

      final xFiles = <XFile>[];
      for (final entry in files.entries) {
        final file = File('${exportDir.path}/${entry.key}');
        await file.writeAsString(entry.value);
        xFiles.add(XFile(file.path));
      }

      if (context.mounted) Navigator.pop(context); // close loading

      await Share.shareXFiles(
        xFiles,
        subject: 'GAX Forge Export: ${project.name}',
        text:
            'Flutter UI code generated by GAX Forge for project "${project.name}"',
      );
    } catch (e) {
      if (context.mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Export failed: $e'),
            backgroundColor: Theme.of(context).colorScheme.error,
          ),
        );
      }
    }
  }

  // ── Screen File Generator ───────────────────
  static String _generateScreenFile(
      GaxProject project, CanvasScreen screen, String className) {
    final buffer = StringBuffer();
    final bgHex = _colorToHex(Color(screen.backgroundColor));

    buffer.writeln("// Generated by GAX Forge - ${project.name}");
    buffer.writeln("// Screen: ${screen.name}");
    buffer.writeln("// Generated on: ${DateTime.now().toIso8601String()}");
    buffer.writeln();
    buffer.writeln("import 'package:flutter/material.dart';");
    buffer.writeln();
    buffer.writeln("class ${className}Screen extends StatelessWidget {");
    buffer.writeln("  const ${className}Screen({super.key});");
    buffer.writeln();
    buffer.writeln("  @override");
    buffer.writeln("  Widget build(BuildContext context) {");
    buffer.writeln("    return Scaffold(");
    buffer.writeln("      backgroundColor: const Color($bgHex),");
    buffer.writeln("      body: Stack(");
    buffer.writeln("        children: [");

    // Sort by zIndex
    final sorted = [...screen.widgets]
      ..sort((a, b) => a.zIndex.compareTo(b.zIndex));

    for (final w in sorted) {
      buffer.writeln(_generatePositioned(w));
    }

    buffer.writeln("        ],");
    buffer.writeln("      ),");
    buffer.writeln("    );");
    buffer.writeln("  }");
    buffer.writeln("}");

    return buffer.toString();
  }

  // ── Positioned Widget Code ──────────────────
  static String _generatePositioned(WidgetProperty w) {
    final p = w.props;
    final indent = '          ';

    String colorVal(String key, [int fallback = 0xFF6750A4]) {
      final v = (p[key] as int?) ?? fallback;
      return 'const Color(${_colorToHex(Color(v))})';
    }

    double dbl(String key, [double fallback = 0]) =>
        (p[key] as num?)?.toDouble() ?? fallback;
    String str(String key, [String fallback = '']) =>
        (p[key] as String?) ?? fallback;
    bool bln(String key, [bool fallback = false]) =>
        (p[key] as bool?) ?? fallback;

    final inner = _generateWidgetCode(w, p, colorVal, dbl, str, bln, indent);

    return '''${indent}Positioned(
${indent}  left: ${w.x.toStringAsFixed(1)},
${indent}  top: ${w.y.toStringAsFixed(1)},
${indent}  width: ${w.width.toStringAsFixed(1)},
${indent}  height: ${w.height.toStringAsFixed(1)},
${indent}  child: $inner,
${indent}),''';
  }

  static String _generateWidgetCode(
    WidgetProperty w,
    Map<String, dynamic> p,
    String Function(String, [int]) colorVal,
    double Function(String, [double]) dbl,
    String Function(String, [String]) str,
    bool Function(String, [bool]) bln,
    String indent,
  ) {
    switch (w.type) {
      case 'Container':
        return '''Container(
${indent}  decoration: BoxDecoration(
${indent}    color: ${colorVal('color')}.withOpacity(${dbl('opacity', 1.0)}),
${indent}    borderRadius: BorderRadius.circular(${dbl('borderRadius', 0)}),${bln('hasBorder') ? '''
${indent}    border: Border.all(
${indent}      color: ${colorVal('borderColor', 0xFF000000)},
${indent}      width: ${dbl('borderWidth', 1)},
${indent}    ),''' : ''}
${indent}  ),
${indent}  padding: EdgeInsets.all(${dbl('padding', 8)}),
${indent})''';

      case 'Text':
        return '''Text(
${indent}  '${_escapeStr(str('text', 'Text Widget'))}',
${indent}  style: TextStyle(
${indent}    fontSize: ${dbl('fontSize', 16)},
${indent}    color: ${colorVal('color', 0xFF000000)},
${indent}    fontWeight: ${str('fontWeight') == 'bold' ? 'FontWeight.bold' : 'FontWeight.normal'},
${indent}  ),
${indent}  textAlign: ${_dartTextAlign(str('textAlign'))},
${indent})''';

      case 'ElevatedButton':
        return '''ElevatedButton(
${indent}  style: ElevatedButton.styleFrom(
${indent}    backgroundColor: ${colorVal('color')},
${indent}    foregroundColor: ${colorVal('textColor', 0xFFFFFFFF)},
${indent}    shape: RoundedRectangleBorder(
${indent}      borderRadius: BorderRadius.circular(${dbl('borderRadius', 12)}),
${indent}    ),
${indent}  ),
${indent}  onPressed: () {},
${indent}  child: Text(
${indent}    '${_escapeStr(str('text', 'Button'))}',
${indent}    style: TextStyle(fontSize: ${dbl('fontSize', 14)}),
${indent}  ),
${indent})''';

      case 'OutlinedButton':
        return '''OutlinedButton(
${indent}  style: OutlinedButton.styleFrom(
${indent}    foregroundColor: ${colorVal('color')},
${indent}    side: BorderSide(color: ${colorVal('color')}),
${indent}    shape: RoundedRectangleBorder(
${indent}      borderRadius: BorderRadius.circular(${dbl('borderRadius', 12)}),
${indent}    ),
${indent}  ),
${indent}  onPressed: () {},
${indent}  child: Text('${_escapeStr(str('text', 'Outlined'))}'),
${indent})''';

      case 'TextButton':
        return '''TextButton(
${indent}  style: TextButton.styleFrom(foregroundColor: ${colorVal('color')}),
${indent}  onPressed: () {},
${indent}  child: Text('${_escapeStr(str('text', 'Text Button'))}'),
${indent})''';

      case 'FilledButton':
        return '''FilledButton(
${indent}  style: FilledButton.styleFrom(backgroundColor: ${colorVal('color')}),
${indent}  onPressed: () {},
${indent}  child: Text('${_escapeStr(str('text', 'Filled'))}'),
${indent})''';

      case 'Card':
        return '''Card(
${indent}  color: ${colorVal('color', 0xFFFFFFFF)},
${indent}  elevation: ${dbl('elevation', 4)},
${indent}  shape: RoundedRectangleBorder(
${indent}    borderRadius: BorderRadius.circular(${dbl('borderRadius', 12)}),
${indent}  ),
${indent}  child: const SizedBox.expand(),
${indent})''';

      case 'TextField':
        return '''TextField(
${indent}  decoration: InputDecoration(
${indent}    hintText: '${_escapeStr(str('hintText', 'Enter text...'))}',
${indent}    labelText: '${_escapeStr(str('labelText', 'Label'))}',
${indent}    border: OutlineInputBorder(
${indent}      borderRadius: BorderRadius.circular(${dbl('borderRadius', 8)}),
${indent}    ),
${indent}  ),
${indent})''';

      case 'Icon':
        return '''Icon(
${indent}  IconData(${(p['iconCode'] as int?) ?? 0xe318}, fontFamily: 'MaterialIcons'),
${indent}  color: ${colorVal('color')},
${indent}  size: ${dbl('size', 32)},
${indent})''';

      case 'CircleAvatar':
        return '''CircleAvatar(
${indent}  backgroundColor: ${colorVal('color')},
${indent}  radius: ${dbl('radius', 30)},
${indent}  child: Text(
${indent}    '${_escapeStr(str('text', 'A'))}',
${indent}    style: TextStyle(
${indent}      color: ${colorVal('textColor', 0xFFFFFFFF)},
${indent}      fontWeight: FontWeight.bold,
${indent}    ),
${indent}  ),
${indent})''';

      case 'Switch':
        return '''StatefulBuilder(
${indent}  builder: (context, setState) {
${indent}    bool _value = ${bln('value', true)};
${indent}    return Switch(
${indent}      value: _value,
${indent}      activeColor: ${colorVal('activeColor')},
${indent}      onChanged: (v) => setState(() => _value = v),
${indent}    );
${indent}  },
${indent})''';

      case 'Checkbox':
        return '''StatefulBuilder(
${indent}  builder: (context, setState) {
${indent}    bool _value = ${bln('value', true)};
${indent}    return Checkbox(
${indent}      value: _value,
${indent}      activeColor: ${colorVal('activeColor')},
${indent}      onChanged: (v) => setState(() => _value = v ?? false),
${indent}    );
${indent}  },
${indent})''';

      case 'Slider':
        return '''StatefulBuilder(
${indent}  builder: (context, setState) {
${indent}    double _value = ${dbl('value', 0.5)};
${indent}    return Slider(
${indent}      value: _value,
${indent}      min: ${dbl('min', 0)},
${indent}      max: ${dbl('max', 1)},
${indent}      activeColor: ${colorVal('activeColor')},
${indent}      onChanged: (v) => setState(() => _value = v),
${indent}    );
${indent}  },
${indent})''';

      case 'LinearProgressIndicator':
        return '''ClipRRect(
${indent}  borderRadius: BorderRadius.circular(4),
${indent}  child: LinearProgressIndicator(
${indent}    value: ${dbl('value', 0.6)},
${indent}    color: ${colorVal('color')},
${indent}    backgroundColor: ${colorVal('backgroundColor', 0xFFE8DEF8)},
${indent}    minHeight: 8,
${indent}  ),
${indent})''';

      case 'CircularProgressIndicator':
        return '''CircularProgressIndicator(color: ${colorVal('color')})''';

      case 'Divider':
        return '''Divider(
${indent}  color: ${colorVal('color', 0xFFCAC4D0)},
${indent}  thickness: ${dbl('thickness', 1)},
${indent})''';

      case 'Chip':
        return '''Chip(
${indent}  label: Text(
${indent}    '${_escapeStr(str('label', 'Chip'))}',
${indent}    style: TextStyle(color: ${colorVal('textColor')}),
${indent}  ),
${indent}  backgroundColor: ${colorVal('color', 0xFFE8DEF8)},
${indent})''';

      case 'FloatingActionButton':
        final mini = bln('mini');
        return mini
            ? '''FloatingActionButton.small(
${indent}  backgroundColor: ${colorVal('color')},
${indent}  onPressed: () {},
${indent}  child: Icon(
${indent}    IconData(${(p['iconCode'] as int?) ?? 0xe145}, fontFamily: 'MaterialIcons'),
${indent}    color: ${colorVal('iconColor', 0xFFFFFFFF)},
${indent}  ),
${indent})'''
            : '''FloatingActionButton(
${indent}  backgroundColor: ${colorVal('color')},
${indent}  onPressed: () {},
${indent}  child: Icon(
${indent}    IconData(${(p['iconCode'] as int?) ?? 0xe145}, fontFamily: 'MaterialIcons'),
${indent}    color: ${colorVal('iconColor', 0xFFFFFFFF)},
${indent}  ),
${indent})''';

      case 'ListTile':
        return '''ListTile(
${indent}  tileColor: ${colorVal('color', 0xFFFFFFFF)},
${indent}  leading: Icon(IconData(${(p['leadingIcon'] as int?) ?? 0xe318}, fontFamily: 'MaterialIcons')),
${indent}  title: Text(
${indent}    '${_escapeStr(str('title', 'List Item'))}',
${indent}    style: TextStyle(color: ${colorVal('textColor', 0xFF000000)}),
${indent}  ),
${indent}  subtitle: Text('${_escapeStr(str('subtitle', 'Subtitle text'))}'),
${indent}  onTap: () {},
${indent})''';

      case 'AppBar':
        return '''AppBar(
${indent}  title: Text(
${indent}    '${_escapeStr(str('title', 'App Bar'))}',
${indent}    style: TextStyle(color: ${colorVal('textColor', 0xFFFFFFFF)}),
${indent}  ),
${indent}  backgroundColor: ${colorVal('color')},
${indent}  centerTitle: ${bln('centerTitle', true)},
${indent})''';

      case 'SnackBar':
        return '''// Note: SnackBars are shown via ScaffoldMessenger
// ScaffoldMessenger.of(context).showSnackBar(
//   SnackBar(
//     content: Text('${_escapeStr(str('message', 'Snackbar message'))}'),
//     backgroundColor: ${colorVal('color', 0xFF323232)},
//   ),
// );
Container(
${indent}  color: ${colorVal('color', 0xFF323232)},
${indent}  padding: const EdgeInsets.symmetric(horizontal: 16),
${indent}  child: Row(
${indent}    children: [
${indent}      Expanded(
${indent}        child: Text(
${indent}          '${_escapeStr(str('message', 'Snackbar message'))}',
${indent}          style: TextStyle(color: ${colorVal('textColor', 0xFFFFFFFF)}),
${indent}        ),
${indent}      ),
${indent}    ],
${indent}  ),
${indent})''';

      default:
        return '''Container(
${indent}  color: ${colorVal('color')},
${indent}  child: const Center(child: Text('${w.type}')),
${indent})''';
    }
  }

  // ── main.dart Generator ─────────────────────
  static String _generateMainFile(GaxProject project) {
    final buffer = StringBuffer();
    final screens = project.screens;

    buffer.writeln("// Generated by GAX Forge");
    buffer.writeln("// Project: ${project.name}");
    buffer.writeln("// ${DateTime.now().toIso8601String()}");
    buffer.writeln();
    buffer.writeln("import 'package:flutter/material.dart';");

    for (final screen in screens) {
      final snake = _toSnakeCase(screen.name);
      final cls = _toClassName(screen.name);
      buffer.writeln("import '${snake}_screen.dart';");
    }

    buffer.writeln();
    buffer.writeln("void main() {");
    buffer.writeln("  runApp(const ${_toClassName(project.name)}App());");
    buffer.writeln("}");
    buffer.writeln();
    buffer.writeln("class ${_toClassName(project.name)}App extends StatelessWidget {");
    buffer.writeln("  const ${_toClassName(project.name)}App({super.key});");
    buffer.writeln();
    buffer.writeln("  @override");
    buffer.writeln("  Widget build(BuildContext context) {");
    buffer.writeln("    return MaterialApp(");
    buffer.writeln("      title: '${project.name}',");
    buffer.writeln("      debugShowCheckedModeBanner: false,");
    buffer.writeln("      theme: ThemeData(");
    buffer.writeln("        useMaterial3: true,");
    buffer.writeln("        colorScheme: ColorScheme.fromSeed(");
    buffer.writeln("          seedColor: const Color(0xFF6750A4),");
    buffer.writeln("        ),");
    buffer.writeln("      ),");
    if (screens.isNotEmpty) {
      final firstCls = _toClassName(screens.first.name);
      buffer.writeln("      home: const ${firstCls}Screen(),");
      if (screens.length > 1) {
        buffer.writeln("      routes: {");
        for (final screen in screens) {
          final cls = _toClassName(screen.name);
          final snake = _toSnakeCase(screen.name);
          buffer.writeln("        '/$snake': (_) => const ${cls}Screen(),");
        }
        buffer.writeln("      },");
      }
    }
    buffer.writeln("    );");
    buffer.writeln("  }");
    buffer.writeln("}");

    return buffer.toString();
  }

  // ── pubspec hint ────────────────────────────
  static String _generatePubspecHint() {
    return '''# GAX Forge Export - pubspec.yaml dependencies hint
# Add these to your pubspec.yaml:

name: your_app_name
description: Generated by GAX Forge

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # No additional packages required for this export
  # All widgets used are from Flutter's standard library

flutter:
  uses-material-design: true
''';
  }

  // ── Helpers ─────────────────────────────────
  static String _colorToHex(Color color) {
    return '0x${color.value.toRadixString(16).toUpperCase().padLeft(8, '0')}';
  }

  static String _escapeStr(String s) =>
      s.replaceAll("'", "\\'").replaceAll('\n', '\\n');

  static String _dartTextAlign(String align) {
    switch (align) {
      case 'center': return 'TextAlign.center';
      case 'right': return 'TextAlign.right';
      default: return 'TextAlign.left';
    }
  }

  static String _toClassName(String name) {
    return name
        .replaceAll(RegExp(r'[^a-zA-Z0-9 ]'), '')
        .split(' ')
        .map((w) => w.isEmpty
            ? ''
            : w[0].toUpperCase() + w.substring(1).toLowerCase())
        .join('');
  }

  static String _toSnakeCase(String name) {
    return name
        .replaceAll(RegExp(r'[^a-zA-Z0-9 ]'), '')
        .trim()
        .toLowerCase()
        .replaceAll(' ', '_');
  }
}
