import 'dart:io';
import 'dart:convert';
import 'package:file_picker/file_picker.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../models/models.dart';

/// Project storage utility - projects ko save/load karne ke liye
/// File system operations yahan handle hain

class ProjectStorage {
  /// Save project as JSON file using file_picker
  static Future<String?> exportProjectAsFile(ProjectModel project) async {
    try {
      final jsonContent = jsonEncode(project.toJson());
      final fileName = '${project.name.replaceAll(' ', '_')}_${project.id.substring(0, 8)}.json';

      final result = await FilePicker.platform.saveFile(
        dialogTitle: 'Export Project',
        fileName: fileName,
        type: FileType.custom,
        allowedExtensions: ['json'],
        bytes: utf8.encode(jsonContent),
      );

      return result;
    } catch (e) {
      print('Error exporting project: $e');
      return null;
    }
  }

  /// Import project from JSON file
  static Future<ProjectModel?> importProjectFromFile() async {
    try {
      final result = await FilePicker.platform.pickFiles(
        dialogTitle: 'Import Project',
        type: FileType.custom,
        allowedExtensions: ['json'],
      );

      if (result != null && result.files.single.path != null) {
        final file = File(result.files.single.path!);
        final content = await file.readAsString();
        final json = jsonDecode(content) as Map<String, dynamic>;
        return ProjectModel.fromJson(json);
      }

      return null;
    } catch (e) {
      print('Error importing project: $e');
      return null;
    }
  }

  /// Export Dart code as .dart file
  static Future<String?> exportDartCode(String code, String projectName) async {
    try {
      final fileName = '${projectName.replaceAll(' ', '_').toLowerCase()}_screen.dart';

      final result = await FilePicker.platform.saveFile(
        dialogTitle: 'Export Dart Code',
        fileName: fileName,
        type: FileType.custom,
        allowedExtensions: ['dart'],
        bytes: utf8.encode(code),
      );

      return result;
    } catch (e) {
      print('Error exporting dart code: $e');
      return null;
    }
  }

  /// Share Dart code using share_plus
  static Future<void> shareDartCode(String code, String projectName) async {
    try {
      final directory = await getTemporaryDirectory();
      final fileName = '${projectName.replaceAll(' ', '_').toLowerCase()}_screen.dart';
      final file = File('${directory.path}/$fileName');

      await file.writeAsString(code);
      await Share.shareXFiles([XFile(file.path)], text: 'Generated by Gax Forge');
    } catch (e) {
      print('Error sharing dart code: $e');
    }
  }

  /// Save code to clipboard (platform specific)
  static Future<void> copyToClipboard(String code) async {
    // Note: For actual clipboard functionality, use flutter/services Clipboard
    // This is a placeholder - actual implementation in ExportBottomSheet
    print('Code copied to clipboard (${code.length} characters)');
  }

  /// Get all saved project files
  static Future<List<File>> getSavedProjectFiles() async {
    try {
      final directory = await getApplicationDocumentsDirectory();
      final projectsDir = Directory('${directory.path}/gax_forge_projects');

      if (!await projectsDir.exists()) {
        return [];
      }

      final files = <File>[];
      await for (var entity in projectsDir.list()) {
        if (entity is File && entity.path.endsWith('.json')) {
          files.add(entity);
        }
      }

      return files;
    } catch (e) {
      print('Error getting saved projects: $e');
      return [];
    }
  }

  /// Delete project file by ID
  static Future<bool> deleteProjectFile(String projectId) async {
    try {
      final directory = await getApplicationDocumentsDirectory();
      final file = File('${directory.path}/gax_forge_projects/$projectId.json');

      if (await file.exists()) {
        await file.delete();
        return true;
      }

      return false;
    } catch (e) {
      print('Error deleting project file: $e');
      return false;
    }
  }
}
